version: '3'
services:

  server:
    build: ./minitwit-web-app
    ports:
      - '15000:15000'

  legacy_tests:
    build:
      context: ./legacy_tests
      dockerfile: pythontests.Dockerfile
    entrypoint: sh -c  "sleep 5 && python /tests/refactored_tests.py"

  tests:
    build: ./tests
    depends_on:
      - server
