version: '3'
services:

  server:
    build: ./go
    ports:
      - '15000:15000'

  tests:
    build:
      context: ./tests
      dockerfile: pythontests.Dockerfile
    entrypoint: sh -c  "sleep 5 && python /tests/refactored_tests.py"

  old_server:
    build: ./old_app
    ports:
      - '5000:5000'






