name: Merge Docs to Main

on:
  push:
    branches:
      - docs
  workflow_dispatch:

permissions:
  actions: write
  contents: write
  deployments: write
  packages: write
  repository-projects: write

jobs:
  merge-docs-to-main:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main branch
        uses: actions/checkout@v4
        with:
          ref: main

      - name: Merge docs branch
        run: |
            git config --global user.name ${{ secrets.BOT_USERNAME }}
            git config --global user.email ${{ secrets.BOT_EMAIL }}
            git fetch origin docs
            git merge --no-ff --no-edit -m "docs update [skip ci]" origin/docs

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.AUTOMATED_RELEASE }}
